import { CardHighlighMotorbikeProps } from "@/components/ui/Cards/CardHighlighMotorbike/card-HighlighMotorbike.types";
import type { CardSingleMotorbikeProps } from "@/components/ui/Cards/CardSingleMotorbike/card-single-motorbike.types";


export const MOCK_MOTORBIKES_HIGHLIGHTED: CardHighlighMotorbikeProps = 
  
  {
      id: "0",
      name: "CB 125F Twister",
      logoSrc: "/images/logotipomoto.png",
      logoAlt: "Honda",
      imagesSrc: ["/images/moto.png","/images/moto2.png","/images/moto3.png"],
      price: "14.700.000",
      originalPrice:"15.700.000",
      buyUrl: "#",
      buttons: true,
      discount:10
  }

export const MOCK_MOTORBIKES: CardSingleMotorbikeProps[] = [
  {
    id: "1",
    name: "CB 125F Twister",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "CB 125F Twister",
    price: "8.990.000",
    buyUrl: "#",
    buttons: true,
    displacement: "125",
     transmission: "manual",
  },
  {
    id: "2",
    name: "CB 190R",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "CB 190R",
    price: "12.490.000",
    originalPrice: "13.500.000",
    buyUrl: "#",
    buttons: true,
    displacement: "150+",
     transmission: "manual",
  },
  {
    id: "3",
    name: "XR 150L",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "XR 150L",
    price: "10.290.000",
    buyUrl: "#",
    buttons: true,
    displacement: "150+",
     transmission: "manual",
  },
  {
    id: "4",
    name: "Wave 110",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "Wave 110",
    price: "5.490.000",
    buyUrl: "#",
    buttons: true,
    displacement: "110",
     transmission: "automatica",
  },
  {
    id: "5",
    name: "CB 500F",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "CB 500F",
    price: "24.990.000",
    originalPrice: "26.000.000",
    buyUrl: "#",
    buttons: true,
    displacement: "150+",
     transmission: "semiautomatica",
  },
  {
    id: "6",
    name: "CG 150 Titan",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "CG 150 Titan",
    price: "9.190.000",
    buyUrl: "#",
    buttons: true,
    displacement: "150+",
     transmission: "manual",
  },
  {
    id: "7",
    name: "Biz 125",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "Biz 125",
    price: "7.290.000",
    buyUrl: "#",
    buttons: true,
    displacement: "125",
     transmission: "automatica",
  },
  {
    id: "8",
    name: "Pop 110i",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "Pop 110i",
    price: "4.890.000",
    buyUrl: "#",
    buttons: true,
    displacement: "110",
     transmission: "automatica",
  },
  {
    id: "9",
    name: "CB 300R",
    logoSrc: "/images/Logo1.png",
    logoAlt: "Honda",
    imageSrc: "/images/CB125F.png",
    imageAlt: "CB 300R",
    price: "16.990.000",
    originalPrice: "18.200.000",
    buyUrl: "#",
    buttons: true,
    displacement: "150+",
     transmission: "eclutch",
  },
];
