import type { Metadata } from "next";
import { Figtree, Manrope } from "next/font/google";
import Header from "@/components/layouts/Global/Header/header";
import MainMenu from "@/components/layouts/MainMenu/main-menu";
import Footer from "@/components/layouts/Global/Footer/footer";
import { NavigationProvider } from "@/components/layouts/NavigationProvider/navigation-provider";
import "./globals.css";
import "@/styles/globals.scss";
import "swiper/css";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavigationProvider>
          <Header />
          <MainMenu />
        </NavigationProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
